apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: my-app
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp-pod
        type: frond-end
    spec:
      containers:
        - name: nginx-conatiner
          image: nginx
  replicas: 3