apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset-for-nodeport
  labels:
    app: my-app-nodeport
    type: front-end-nodeport
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: my-app-nodeport
        type: frond-end-nodeport
    spec:
      containers:
        - name: nginx-conatiner
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: frond-end-nodeport